### ISSUE TITLE
大佬  多文件选择 下载有问题

### ISSUE THREAD

**Issue by xjy12345654** [cll123456/deal-big-file#1]
不支持多文件选择 ，（在努力学习大佬源码，尝试抽取改造成原生js） 下载时 浏览器控制台 提示 Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.  能否在不设置浏览器的情况下加以解决呢？

**Comment by cll123456** [comment]
> 

您好，能提供一个问题的链接么

**Comment by xjy12345654** [comment]
> > 
> 
> 您好，能提供一个问题的链接么

 在本地测试的，先用你的demo跑的 上传模块正常，下载不成功。  https://blog.csdn.net/WHQ78164/article/details/120566824

**Comment by cll123456** [comment]
下载用的是 `streamsaver` 这个现有的库来做的，貌似这个库里面用到的 `WritableStream `的兼容性挺好的，不应该会有问题。
![image](https://user-images.githubusercontent.com/41314419/190310644-3b107f7e-4de5-4a75-ace3-1bf44eb1bebc.png)

我看你的文章里面用的是 使用[selenium](https://so.csdn.net/so/search?q=selenium&spm=1001.2101.3001.7020)操作无头模式，是不是有影响呢？

> > > 
> > 
> > 
> > 您好，能提供一个问题的链接么
> 
> 在本地测试的，先用你的demo跑的 上传模块正常，下载不成功。 https://blog.csdn.net/WHQ78164/article/details/120566824

**Comment by xjy12345654** [comment]
> 下载用的是 `streamsaver` 这个现有的库来做的，貌似这个库里面用到的 `WritableStream `的兼容性挺好的，不应该会有问题。 ![image](https://user-images.githubusercontent.com/41314419/190310644-3b107f7e-4de5-4a75-ace3-1bf44eb1bebc.png)
> 
> 我看你的文章里面用的是 使用[selenium](https://so.csdn.net/so/search?q=selenium&spm=1001.2101.3001.7020)操作无头模式，是不是有影响呢？
> 
> > > > 
> > > 
> > > 
> > > 您好，能提供一个问题的链接么
> > 
> > 
> > 在本地测试的，先用你的demo跑的 上传模块正常，下载不成功。 https://blog.csdn.net/WHQ78164/article/details/120566824

能给个联系方式吗 大佬，自己想请教下源码中的部分内容
